FROM golang:1.24.5-alpine3.21

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /go-finance-app ./cmd/server

EXPOSE 8080

CMD ["/go-finance-app"]